blueprint:
  name: Light Switch
  description: Turn on light, when physical switch pressed
  domain: automation
  source_url: https://github.com/IngmarBuchenhain/HomeAutomationFiles/blob/1316be96442b2db9680b916aee049867cbb14d00/light_switch.yaml
  input:
    switch_entity:
      name: Light switch
      selector:
        entity:
          domain: binary_sensor
          device_class: presence
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

trigger:
  platform: state
  entity_id: !input switch_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.toggle
    target: !input light_target

