blueprint:
  name: Light Switch with two lights
  description: Turn on lights, when physical switch pressed
  domain: automation
  source_url: https://github.com/IngmarBuchenhain/HomeAutomationFiles/blob/main/light_switch_multiple.yaml
  input:
    switch_entity:
      name: Light switch
      selector:
        entity:
          domain: binary_sensor
          device_class: presence
    light_target0:
      name: Light
      selector:
        target:
          entity:
            domain: light
    light_target1:
      name: Light
      selector:
        target:
          entity:
            domain: light

trigger:
  platform: state
  entity_id: !input switch_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.toggle
    target: !input light_target0
  - alias: "Turn on the light"
    service: light.toggle
    target: !input light_target1

