esphome:
  name: first-floor-main-room

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Your_Key"

ota:
  password: "Your_Key"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "First-Floor-Main-Room"
    password: "Your_Key"

captive_portal:

# Temperature
sensor:
  - platform: dht
    pin: GPIO15 # D8
    temperature:
      name: "First Floor Main Room Temperature"
    humidity:
      name: "First Floor Main Room Humidity"
    update_interval: 5s

# # Ambient night light
# switch:
#   - platform: gpio
#     pin: 1 #choose a free pin here, just to make ESPHome happy. we do not need it for anything
#     name: "First Floor Ambient Night Light"
#     on_turn_on:
#     - light.addressable_set:
#             id: "ffmr_rgb_light"
#             range_from: 0
#             range_to: 1
#             color_brightness: 0.3
#             red: 1
#             blue: 0
#             green: 0
#     on_turn_off:
#     - light.addressable_set:
#             id: "ffmr_rgb_light"
#             range_from: 0
#             range_to: 1
#             color_brightness: 0
#             red: 0
#             blue: 0
#             green: 0

number:
# Heater Thermostat
  - platform: template
    name: First Floor Main Room Thermostat
    min_value: 5
    max_value: 25
    step: 0.5
    optimistic: true
    set_action:
      then:
        - light.addressable_set:
            id: "ffmr_rgb_light"
            range_from: 0
            range_to: 1
            color_brightness: !lambda 'return x/25.0;'
            red: !lambda 'return ((x-5)*5)/100.0;'
            blue: !lambda 'return (100-(x-5)*5)/100.0;'
            green: 0

# Sensors for contact and light switch
binary_sensor:
  - platform: gpio
    pin: 12 # D6
    name: "First Floor Main Room Light Switch"
    device_class: presence
  - platform: gpio
    pin:
      number: GPIO4 # D2
      inverted: True
    name: "First Floor Main Room Door Contact 2"
    device_class: door
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin:
      number: GPIO5 # D1
      inverted: True
    name: "First Floor Main Room Door Contact 1"
    device_class: door
    filters:
      - delayed_on: 10ms
  - platform: gpio
    pin: 16 # D0
    name: "First Floor Main Room Motion"
    device_class: motion

# Lights
light:
  - platform: binary
    name: "First Floor Main Room Light"
    output: light_output_main_room
  - platform: binary
    name: "First Floor Bath Room Light"
    output: light_output_bath_room
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO13 # D7
    id: "ffmr_rgb_light"
    num_leds: 2
    name: "First Floor Main Room Heater"
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO14 # D5 
    num_leds: 9
    name: "First Floor Main Room Ambient Light"

# Outputs for light
output:
  - id: light_output_main_room
    platform: gpio
    pin: GPIO0 # D3
  - id: light_output_bath_room
    platform: gpio
    pin: GPIO2 # D4

