esphome:
  name: first-floor-bed-room

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Your_Key"

ota:
  password: "Your_Key"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "First-Floor-Bed-Room"
    password: "Your_Key"

captive_portal:

# Lights
light:
  - platform: binary
    name: "First Floor Bed Room Light"
    output: light_output_bed_room
  - platform: binary
    name: "First Floor Alarm Light"
    output: light_output_alarm
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO0 # D3
    num_leds: 2
    id: "ffbr_rgb_light"
    name: "First Floor Bed Room Heater"

# Example configuration entry
sensor:
  - platform: bh1750
    name: "First Floor Bed Room Luminescence"
    address: 0x23
    update_interval: 2s

# Input for light sensor
i2c:
  sda: 5  # D1
  scl: 4  # D2
  scan: true
 
# Servo and Heater
number:
# Window Louvre  
  - platform: template
    name: First Floor Bed Room Window Louvre
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: window_louvre_servo
            level: !lambda 'return x / 50.0 - 1;'  
# Heater Thermostat
  - platform: template
    name: First Floor Bed Room Thermostat
    min_value: 5
    max_value: 25
    step: 0.5
    optimistic: true
    set_action:
      then:
        - light.addressable_set:
            id: "ffbr_rgb_light"
            range_from: 0
            range_to: 1
            color_brightness: !lambda 'return x/25.0;'
            red: !lambda 'return ((x-5)*5)/100.0;'
            blue: !lambda 'return (100-(x-5)*5)/100.0;'
            green: 0

# Servo Transition
servo:
  - id: window_louvre_servo
    output: pwm_output_window_louvre
    transition_length: 1s

# Output for light and servo
output:
  - platform: esp8266_pwm
    id: pwm_output_window_louvre
    pin: GPIO2 # D4
    frequency: 50 Hz
  - id: light_output_bed_room
    platform: gpio
    pin: GPIO14 # D5
  - id: light_output_alarm
    platform: gpio
    pin: GPIO12 # D6
