esphome:
  name: ground-floor-main-room

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Your_Key"

ota:
  password: "Your_Key"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ground-Floor-Main-Room"
    password: "Your_Key"

captive_portal:
    
# Luminescence and temperature
sensor:
  - platform: dht
    pin: GPIO13 # D7
    temperature:
      name: "Ground Floor Main Room Temperature"
    humidity:
      name: "Ground Floor Main Room Humidity"
    update_interval: 5s
  - platform: bh1750
    name: "Ground Floor Main Room Luminescence"
    address: 0x23
    update_interval: 2s

binary_sensor:
  - platform: gpio
    pin: 0 # D3
    name: "Ground Floor Main Room Light Switch"
    device_class: presence

# Lights
light:
  - platform: binary
    name: "Ground Floor Main Room Light"
    output: light_output_main_room
  - platform: binary
    name: "Ground Floor Kitchen Room Light"
    output: light_output_kitchen_room
  - platform: neopixelbus
    type: GRB
    variant: WS2812
    pin: GPIO15 # D8
    num_leds: 2
    id: gfmr_rgb_light
    name: "Ground Floor Main Room Heater"

number:
# Heater Thermostat
  - platform: template
    name: Ground Floor Main Room Thermostat
    min_value: 5
    max_value: 25
    step: 0.5
    optimistic: true
    set_action:
      then:
        - light.addressable_set:
            id: "gfmr_rgb_light"
            range_from: 0
            range_to: 1
            color_brightness: !lambda 'return x/25.0;'
            red: !lambda 'return ((x-5)*5)/100.0;'
            blue: !lambda 'return (100-(x-5)*5)/100.0;'
            green: 0    

# Output for lights
output:
  - id: light_output_main_room
    platform: gpio
    pin: GPIO14 # D5
  - id: light_output_kitchen_room
    platform: gpio
    pin: GPIO12 # D6

# BH1750 input
i2c:
  sda: 5 # D1
  scl: 4 # D2
  scan: true
