esphome:
  name: ground-floor-door-area

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Your_Key"

ota:
  password: "Your_Key"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ground-Floor-Door-Area"
    password: "Your_Key"

captive_portal:
    
esp32_camera:
  name: "Ground Floor Door Area Camera"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  vertical_flip: false

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

binary_sensor:
  - platform: status
    name: "Ground Floor Door Area Camera Status"
    
sensor:
  - platform: wifi_signal
    name: "Ground Floor Door Area Camera WiFi Signal"
    update_interval: 60s
    
light:
  - platform: binary
    output: gpio_4
    name: "Ground Floor Door Area Camera Light"
