# PINs  Komponente
# 1,2   Helligkeitssensor
# 3     Heizungs RgbLed
# 4     Ventilatorrelais
# 5     Lichtschalter
# 6     Bewegungsmelder
# 7     Reed-Kontakt
# 8     Hauptbeleuchtung
# 0     Temperatur und Feuchtigkeitssensor

esphome:
  name: "og2t-board"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HierKoennteIhrKeyStehen"

ota:
  password: "HierKoennteIhrKeyStehen"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "OG2-Treppenhaus Fallback Hotspot"
    password: "HierKoennteIhrKeyStehen"

captive_portal:

binary_sensor:
# Bewegungsmelder
  - platform: gpio
    pin: D6
    name: "OG2 Treppenhaus Bewegungsmelder"
    device_class: motion
# Lichtschalter (Touch)
  - platform: gpio
    pin:
      number: D5
      mode:
        input: true
        pullup: true
    name: "OG2 Treppenhaus Lichtschalter"
    filters:
      - delayed_off: 50ms
# Reed-Kontakt
  - platform: gpio
    pin:
      number: D7
      inverted: true
    name: "OG2 Treppenhaus Fenster"
    device_class: opening
    filters:
      - delayed_off: 50ms

light:
# Hauptbeleuchtung
  - platform: binary
    output: "og2_treppenhaus_led"
    name: "OG2 Treppenhaus Licht"
    id: "og2_treppenhaus_licht"
# Heizungs-LED
  - platform: neopixelbus
    id: "og2_treppenhaus_heizungs_led"
    type: GRB
    variant: WS2812X
    pin: D3
    num_leds: 2

number:
# Heizung Thermostat
  - platform: template
    name: OG2 Treppenhaus Heizung Thermostat
    min_value: 5
    max_value: 25
    step: 0.5
    optimistic: true
    set_action:
      then:
        - light.addressable_set:
            id: og2_treppenhaus_heizungs_led
            range_from: 0
            range_to: 1
            color_brightness: !lambda 'return x/25.0;'
            red: !lambda 'return ((x-5)*5)/100.0;'
            blue: !lambda 'return (100-(x-5)*5)/100.0;'
            green: 0.0
            
# Helligkeitssensor
i2c:
  scl: D1
  sda: D2
  scan: true
  frequency: 100kHz 

sensor:
# Helligkeitssensor
  - platform: bh1750
    name: "OG2 Treppenhaus Helligkeitssensor"
    address: 0x23
    update_interval: 60s
# Temperatur und Feuchtigkeitssensor
  - platform: dht
    pin: D0
    model: DHT22
    temperature:
      name: "OG2 Treppenhaus Temperatur"
    humidity:
      name: "OG2 Treppenhaus Luftfeuchtigkeit"
    update_interval: 60s

switch:
# Ventilatorrelais
  - platform: gpio
    pin: D4
    name: "OG2 Treppenhaus Ventilator"
    id: "og2_treppenhaus_ventilator"

output:
# Hauptbeleuchtung-Output
  - platform: gpio
    pin: D8
    id: "og2_treppenhaus_led"
